language: csharp

dotnet: 2.1.502
sudo: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - dotnet build FileManagerWithProfiles.sln -c Release

    - dotnet test -c Release --no-build FileManagerWithProfiles.UnitTests/FileManagerWithProfiles.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover