language: csharp

dotnet: 3.0.100

sudo: required

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/

script:
    - dotnet build FileManagerWithProfiles.sln -c Release

    - dotnet test -c Release --no-build FileManagerWithProfiles.UnitTests/FileManagerWithProfiles.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
    - bash <(curl -s https://codecov.io/bash)